# Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.
ans:

In [3]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [15]:
import numpy as np
a=[]
b=[]
for i in range(5):
    x=int(input())
    a.append(x)
print(a)
for i in range(5):
    y=int(input())
    b.append(y)
print(b)
arr1=np.array(a)
arr2=np.array(b)
arr=np.concatenate((arr1,arr2))
print(arr)
print(np.sort(arr))

9
8
7
6
5
[9, 8, 7, 6, 5]
4
3
2
1
0
[4, 3, 2, 1, 0]
[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


# Question 3

Write a code snippet to find the dimensions of a ndarray and its size.

In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])# the ndarray
print(arr.ndim)# for getting the dimension of array
print(arr.size)# for getting the size of the array


2
6


# Question 4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [13]:
import numpy as np

arr = np.arange(10)
print(arr)

print("Shape of Array :",arr.shape)# 1D array

row_arr = arr[np.newaxis, :]
print("\nShape of 2d Array in row major :",row_arr.shape)# 2D array
print(row_arr)
col_arr = arr[:, np.newaxis]
print("\nShape of 2d Array in column major :",col_arr.shape)# 2D array
print(col_arr)
row_arr = np.expand_dims(arr, axis=0)
print("\nShape of 2d Array in row major :",row_arr.shape)# 2D array
print(row_arr)
col_arr = np.expand_dims(arr, axis=1)
print("\nShape of 2d Array in column major :",col_arr.shape)# 2D array
print(col_arr)


[0 1 2 3 4 5 6 7 8 9]
Shape of Array : (10,)

Shape of 2d Array in row major : (1, 10)
[[0 1 2 3 4 5 6 7 8 9]]

Shape of 2d Array in column major : (10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

Shape of 2d Array in row major : (1, 10)
[[0 1 2 3 4 5 6 7 8 9]]

Shape of 2d Array in column major : (10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


# Question 5

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [17]:
import numpy as np
arr_1 = np.arange(0,4)
arr_2 = np.arange(5,9)
arr_v = np.vstack((arr_1,arr_2))
print(arr_v)
arr_h = np.hstack((arr_1,arr_2))
print(arr_h)



[[0 1 2 3]
 [5 6 7 8]]
[0 1 2 3 5 6 7 8]


# Question 6

How to get unique items and counts of unique items?

In [32]:
a = np.array([45,6,4,34,6,7,8,3,4,53,6,7,8,5,5])

u, indices = np.unique(a, return_counts=True)
print(u) #unique items
print(indices) # counts of unique items

[ 3  4  5  6  7  8 34 45 53]
[1 2 2 3 2 2 1 1 1]
